### ISSUE TITLE
USWDS - Bug: 508 - Unable to focus on the clear mark for the search field

### ISSUE THREAD

**Issue by yerramshilpa** [uswds/uswds#5786] opened 2024-02-23 15:15 UTC
### Describe the bug

A User cannot focus on the clear mark in the search field by a tab key. 

### Steps to reproduce the bug

1. Go to https://designsystem.digital.gov/components/search/
2. Type some text in the search input and hit the tab
3. x clear icon is not able to focus with the tab key 

### Expected Behavior

When you type something in the search input and hit the tab key, it should highlight the (x) clear icon instead of the search button.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by brunerae** [comment] 2024-02-23 17:51
Tagging in @amyleadem for confirmation

**Comment by aduth** [comment] 2024-02-29 18:50
Is this the same as #5277 ?

**Comment by yerramshilpa** [comment] 2024-02-29 19:14
Yes same issue

**Comment by amyleadem** [comment] 2024-03-04 22:06
Closing this as a duplicate of #5277

**Closed by amyleadem** 2024-03-04 22:06 UTC
Labels: Type: Bug, Needs: Confirmation
