### ISSUE TITLE
USWDS - Bug: Table header cells in table body do not get header styling

### ISSUE THREAD

**Issue by ajanickiv** [uswds/uswds#5777] opened 2024-02-20 15:15 UTC
### Describe the bug

Table row elements <tr> in a table body <tbody> can have table header elements <th>. When using the `usa-table` class on a table these table header cells are not styled like the table header cells in the table header <thead> element.
![image](https://github.com/uswds/uswds/assets/16595489/b491de64-c752-4906-8ea3-55bc1ef4fe37)

### Steps to reproduce the bug

1. Create a table with the `usa-table` class with a th tag nested in a tr tag nested in a tbody tag

### Expected Behavior

a th tag nested in a tr tag nested in a tbody tag should be styled as header cells
![image](https://github.com/uswds/uswds/assets/16595489/fb063db4-d20b-4a04-821e-7e0c70a11731)

### Related code
Table code
```
<tbody>
        <tr>
          <th>Zodiac</th>
          <td>A2</td>
          <td>A3</td>
          <td>A4</td>
        </tr>
</tbody>
```

I think the `.usa-table tbody th` needs added to the existing header styling css block like this.
```
.usa-table thead th,
.usa-table tbody th {
  background-clip: padding-box;
  font-weight: 700;
  line-height: 1.3;
}

.usa-table thead td,
.usa-table thead th,
.usa-table tbody th {
  background-color: #dfe1e2;
  color: #1b1b1b;
}
```

https://stackblitz.com/edit/stackblitz-starters-eeh9oc?file=index.html

### System setup

- USWDS version 3.7.1

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by brunerae** [comment] 2024-02-23 18:00
Assigning to @amyleadem to identify if this is expected behavior (perhaps comparing against native browser behavior) or a bug.

**Comment by mejiaj** [comment] 2024-02-23 18:02
We can use https://www.w3.org/WAI/tutorials/tables/ examples from uswds/uswds-site#2261 to confirm native browser behavior.

**Comment by cathybaptista** [comment] 2024-07-11 18:46
Issue confirmed with #5779 

#5779 includes 3 commits: https://github.com/uswds/uswds/pull/5779/commits, the last one (22b609d5d15ddd413971e2412a04a3dd99ea5c18) has to do with accessibility.

**Comment by mahoneycm** [comment] 2024-07-15 14:28
The work in #5779 contains multiple markup changes, which we consider breaking changes. We should review carefully and make sure we're only updating what is relevant to the row heading styling issue.

I believe the `th` elements that were changed to `td` are intended to be table row headers. We may want to consider updating the values of the table to demonstrate this idea more clearly if that is not clear.

**Closed** 2024-12-16 23:09 UTC
Labels: Type: Bug
