### ISSUE TITLE
2.13.3 breaks accordion footers

### ISSUE THREAD

**Issue by smustgrave** [uswds/uswds#4632] opened 2022-04-16 00:24 UTC
### Describe the bug
Prior to 2.13.3 the menu's in the footer would turn to accordions in mobile but now they break.
footer.js:57 Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
    at footer.js:57:41
    at NodeList.forEach (<anonymous>)
    at u (footer.js:43:16)
    at Object.init (footer.js:82:7)
    at behavior.js:15:22
    at Array.forEach (<anonymous>)
    at Object.on (behavior.js:13:9)
    at start.js:22:14
    at Array.forEach (<anonymous>)
    at start.js:20:27

**Comment by smustgrave** [comment] 2022-04-16 00:27
Also not sure how but the mobile menu stopped working.  Assuming a symptom of the error above.

**Comment by amyleadem** [comment] 2022-04-18 17:12
Hello @smustgrave, thank you for sharing this issue with us. I am not able to reproduce this error. Would you be able to share relevant code (particularly your footer markup) or a preview link so that we can see the issue in action?

**Comment by smustgrave** [comment] 2022-04-18 18:13
So not sure if this helps but this is a Drupal website.

[footer.txt](https://github.com/uswds/uswds/files/8507297/footer.txt)

Here's my footer html.  We reverted back to 2.13.2 and it started working again.

**Comment by amyleadem** [comment] 2022-05-05 15:50
Hello @smustgrave, I apologize for my delayed response. 

In looking through your markup, I noticed that you had a `<strong>` element wrapping your `usa-footer__primary-link` elements. From your footer.txt: `<strong><span class="nolink usa-footer__primary-link">US Navy</span></strong>`

In [2.13.3](https://github.com/uswds/uswds/releases/tag/v2.13.3), we [updated our footer JS to be more accessible](https://github.com/uswds/uswds/pull/4476), and in doing so created new reliance on our current markup structure, particularly surrounding the `usa-footer__primary-link` element. 

My suspicion is that because you are wrapping your `usa-footer__primary-link` element with a `<strong>` element, the new JS is not able to find  the appropriate sibling, and it is sending you that `null` error. 

Can you update your markup to [match ours](https://github.com/uswds/uswds/blob/release-2.13.2/src/components/footer/footer--big.njk#L22) and let me know if it still gives you trouble? 
Please let me know if you have any questions. 

Thanks!

**Comment by mejiaj** [comment] 2022-05-09 13:37
Fixed in #4668.

**Closed by mejiaj** 2022-05-09 13:37 UTC
Labels: Affects: Footer
