### ISSUE TITLE
USWDS - Bug: Release has bogus file dates

### ISSUE THREAD

**Issue by bkline** [uswds/uswds#5746] opened 2024-01-25 21:52 UTC
### Describe the bug

The tar file for the latest release has files with timestamps back in October 26, 1985.

### Steps to reproduce the bug

1. Download https://github.com/uswds/uswds/releases/download/v3.7.1/uswds-uswds-3.7.1.tgz
2. Unpack the tarfile
3. Look at the timestamps on the unpacked file

### Expected Behavior

The files in the release tar file correctly reflect the date/time of creation.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by mejiaj** [comment] 2024-01-26 00:31
Thanks for reporting @bkline!

Confirming on mac OS 14.1.1. 
<img width="800" alt="image" src="https://github.com/uswds/uswds/assets/3385219/15004a3f-8d49-46ee-88d0-f346e3d35a0a">

Need to look into possible NPM issue and release script. This is using built-in `npm pack`, so no security concerns.

https://github.com/uswds/uswds/blob/202448875393d39d663614d2d8f9a12c91fed75e/tasks/release.js#L37

**Comment by mahoneycm** [comment] 2024-02-08 20:40
It looks like this is actually the _intended behavior_ from the node team based on this [issue](https://github.com/npm/npm/issues/19968) discussion.

> The reason for this was so two separate npm pack calls done from the same commit -- even on separate computers, would be able to generate hash-identical tarballs. We didn't really expect that random software out there would have... pathological issues with old timestamps. We still want to preserve the feature, though, so picking an arbitrary date more recent than 1980 seemed like the way to go. Hopefully there's no more incompatibilities! [^1]
>
> We have every intention of keeping the consistent dates going forward because they enable reproducible builds for npm packages. [^2]

[^1]: https://github.com/npm/npm/issues/19968#issuecomment-372799983
[^2]: https://github.com/npm/npm/issues/19968#issuecomment-383988984

**Comment by mejiaj** [comment] 2024-02-16 15:01
@mahoneycm thanks for looking into it. You're right, we'll need to discuss whether we continue for find an alternative.

**Comment by bkline** [comment] 2024-02-16 18:04
If nothing else, assuming this odd practice is continued, I would strongly suggest a prominent notice explaining the dates which otherwise seem highly suspicious, and suggest tampering.

**Comment by mahoneycm** [comment] 2024-02-23 21:28
Since this is intended NPM behavior, we are going to close this ticket and update the website with the following note to inform users:

> **Note**: The file date defaults to October 26, 1985, when you download and install this package. This is intentional. NPM sets a default date to ensure reproducible builds for npm packages.

We will continue to track this work at uswds/uswds-site#2499.

Thank you for flagging @bkline !

**Closed by mahoneycm** 2024-02-23 21:28 UTC
Labels: Type: Bug, Needs: Discussion, Affects: Dependencies
