### ISSUE TITLE
Inconsistent font sizing with Accordion in Chrome on Android

### ISSUE THREAD

**Issue by pglevy** [uswds/uswds#4249] opened 2021-07-02 18:02 UTC
### Describe the bug
When viewing the Accordion component on mobile Chrome (on Android), some button labels are displayed at larger sizes than others at small screen widths. It seems to be an issue with longer labels.

### Steps to reproduce the bug
1. Create a page with the accordion component and enter some content, some with longer labels (around 100 characters).
2. View the page on mobile Chrome on Android in portrait orientation. (Not able to reproduce in "responsive" view on a desktop browser.)
3. Note differences in button label font size.

### Expected behavior
Font sizes should be consistent.

It seems to be an issue with "[font boosting/inflation](https://stackoverflow.com/questions/13430897/how-to-override-font-boosting-in-mobile-chrome)" built into mobile Chrome, but the hacks and CSS settings mentioned in the thread didn't work for me.

On my phone, the component displays as expected when rotating to landscape orientation so it seems to be affected by the `@media` rule screen size.

### Screenshots
Two shots of the same page on the same phone. One portrait, one landscape.

Portait:
![image](https://user-images.githubusercontent.com/5177337/124312671-b456af80-db3d-11eb-8bc3-afa21150c987.png)

Landscape: 
![image](https://user-images.githubusercontent.com/5177337/124312731-c89aac80-db3d-11eb-8c28-a0c405d6e413.png)

### System setup
- **USWDS version:** 2.11.1
- **Device:** Samsung Galaxy A50 (SM-A505U)
- **Operating system:** Android 11
- **Browser and version:** Mobile Chrome 91

### Additional context
None.

**Comment by mejiaj** [comment] 2022-07-06 19:24
Unable to reproduce, checked several older android devices on Browserstack.

Including:
- Nexus 7
- Pixel
- Samsung Tab S7
- Samsung Galaxy A51

**Comment by thisisdano** [comment] 2022-07-27 17:08
Closing since we can't reproduce this

**Closed by thisisdano** 2022-07-27 17:08 UTC
Labels: Status: Can't Reproduce, Package: Accordion, Context: Android, Context: Chrome
