### ISSUE TITLE
Add Medium and GitHub classes

### ISSUE THREAD

**Issue by fulldecent** [uswds/uswds#1752] opened 2017-03-01 20:23 UTC
You currently have `usa-link-twitter`.

Please also add:

 * `usa-link-medium`
 * `usa-link-github`

Here is an agency website that uses those:

https://www.dds.mil/

**Comment by maya** [comment] 2018-02-21 23:09
Added documentation around how to add additional social media classes here: https://github.com/uswds/uswds-site/pull/502 Let us know if this helps with or resolves this issue @fulldecent.

**Comment by maya** [comment] 2018-02-21 23:12
Noticed this is a duplicate of #1800, so moving conversation there.

**Closed by maya** 2018-02-21 23:12 UTC
Labels: [Priority] Minor, [Skill] Front end, [Skill] UX, [Type] Enhancement
