### ISSUE TITLE
Screen reader announces radio and text with optional text multiple times

### ISSUE THREAD

**Issue by jmdembe** [uswds/uswds#4550] opened 2022-03-01 20:25 UTC
### Describe the bug
We (the Login.gov team) have implemented the checkbox and radio buttons with optional text to the Login Design System. The Login design system is built on top of USWDS.

When testing a form using a screen reader (specifically in Chrome using JAWS and NVDA), I found that when a user reads or scans the entire page, content within the label is announced twice. For example, in the USWDS component for radio buttons, The tile for Fredrick Douglass will be announced. Upon announcement, the label text is read with the radio button as well as the text inside the label element.

### Steps to reproduce the bug
1. Go to https://designsystem.digital.gov/components/radio-buttons/
2. Access the Component preview using the tab keys to interact with that element. Tab until you land on the component preview button
3. Turn on your screen reader. In this case, I used JAWS. Further directions assume that you are using JAWS.
4. Have the screen reader announce the elements in the component preview
5. Listen carefully to the tile that reads "Fredrick Douglass This is optional text that can be used to describe the label in more detail"

### Expected behavior
I would expect that the text in that specific label to be read once.

### Screenshots

https://user-images.githubusercontent.com/17969963/156243098-38cc7ca5-305e-4623-ab1b-b1b794c67cb3.mov

### System setup
- **USWDS version:** 2.13.1
- **Device:** Laptop: Mac using a Windows virtual environment
- **Operating system:** Windows 11
- **Browser and version:** Chrome v98.0.4758.102

### Additional context
- Tagging @aduth and for visibility as he manages the Login design system as well

Caveats:
- The issue is **not** seen when testing on Safari using VoiceOver
- The problem occurs when you are reading/scanning the entire page. If a user navigates using an interactive element, the problem does not occur.

**Comment by brunerae** [comment] 2022-06-22 18:15
@thisisdano - the 508 team did a deep dive and everything looks good. They also tested on Safari/VoiceOver and confirmed its reading each radio button twice.

**Comment by amyleadem** [comment] 2022-08-03 15:56
Curious to get some opinions on expected behavior on this and whether to consider this a bug. 

I was able to navigate through the elements without content repeating when I used standard navigation interactions (details below). The issue occurs when trying to navigate through individual elements on the page, either by using `VO` + `A` (to read through all page content) or `VO` + `right-arrow`/`left-arrow` (to move to next/previous element). 

This appears not to be an issue with our code specifically (with possibly the exception of recommending including a span inside a label), but instead a consistent result with standard html radio and checkbox examples.

Note: Results vary across browsers. Example: Safari repeated all elements when navigating by individual element, Chrome only repeated when the label span was present.

@mejiaj  Can you test on NVDA and let me know if you achieve the same results with the  navigation methods listed below?

## Radio Buttons
Radio groups require modified navigation techniques from the `tab` default, but it appears there are standards radio group keyboard interaction. References from W3 and Mozilla below. 

- After testing in VoiceOver, I discovered that content:
    - does NOT repeat when following these steps:
        1. Open [radio component in Storybook](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-form-inputs-radio--default&viewMode=story)
        1. Turn on VoiceOver
        1. Tab into the radio group (should focus only on the selected item)
        1. Once you enter the radio group, use left/right or up/down arrows to navigate the radio items OR
        1. Jump to the form elements with `VO` + `Cmd` + `J`
    - Does repeat when following these steps:
        1. Open [radio component in Storybook](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/develop/iframe.html?args=&id=components-form-inputs-radio--default&viewMode=story)
        1. Turn on VoiceOver
        1. Press VO + A to read all page contents, OR
        1. Use VO + right/left to navigate content by each element
        
**Reference: expected keyboard interaction for radio groups**
In VoiceOver, our readouts appear to match readouts from this demo from Mozilla.
- From [Mozilla](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role#keyboard_interactions):

> `Tab + Shift`
>Move focus into and out of the radio group. When focus moves into a radio group, and a radio button is already checked, focus is set on the checked button. If none of the radio buttons are checked, focus is set on the first radio button in the group.
>
> `Space`
> Checks the radio if not already checked. Unchecks a previously checked radio button in the radio group.
>
> `Right Arrow and Down Arrow`
Move focus to and checks the next radio button in the group, unchecking the previously focused radio button. If focus is on the last radio button, focus moves to the first radio button.
>
> `Left Arrow and Up Arrow`
> Move focus to and checks the previous radio button in the group, unchecking the previously focused radio button. If focus is on the first radio button, focus moves to the last radio button."

- Similar instructions from W3: https://www.w3.org/wiki/RadioButton

**For comparison: radio group code demo from Mozilla**
https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-radio.html

## Checkbox
- Could navigate all elements via standard `tab` navigation without repetition. 
- Encountered repetition when navigating via `VO` + `A` or `VO` + `left-arrow`/`right-arrow`.
- W3 Checkbox keyboard interaction: https://www.w3.org/wiki/CheckBox

**For comparison: checkbox code demo from Mozilla**
https://interactive-examples.mdn.mozilla.net/pages/tabbed/input-checkbox.html

**Comment by mejiaj** [comment] 2022-08-03 16:23
@amyleadem I couldn't reproduce using NVDA 2022.2 on Windows. Using latest USWDS on `develop` (v3.0.2).

I checked radio buttons on both site and storybook in:
- [x] Chrome v103
- [x] Firefox v104
- [x] Edge v103

**Comment by amyleadem** [comment] 2022-08-11 18:14
Closing this issue with the label `Status: Not a bug` because we were able to achieve desired results using standard keyboard form navigation techniques. 

In addition, I have added the labels `Possible future enhancement` and `Needs: Research` so that we can return to this if we get the opportunity to research real world behavior for keyboard navigation and discover that the issue outlined here is common user behavior.

**Closed by amyleadem** 2022-08-11 18:14 UTC
Labels: Affects: Accessibility 🟡, Needs: Discussion, Status: Not a Bug, Good First Issue, Context: NVDA, Context: JAWS, Needs: Research, Possible future enhancement
