### ISSUE TITLE
Illogical Tab Order in header

### ISSUE THREAD

**Issue by davidstenger** [uswds/uswds#1651] opened 2016-12-21 18:36 UTC
**Issue**:
When tabbing through the page the tab order does not match the visual order of the page. Currently, after the Department of Web Standards link users tab to the Section Title link instead of Search link. This does not match the visual order of the screen. 
See attachment [TabOrder_ExtendedHeader.png](https://drive.google.com/open?id=0ByQeU_iOqP_ieFNoeGNrOHlhTG8)

Same issue is presented in responsibe view. 

**Solution**:
Update the tab order so that when navigating through the page the user proceeds from left to right, top to bottom. This can be done by altering the order of the items within the HTML source code to match the visual order of the page.

**Comment by toolness** [comment] 2017-07-13 23:03
I'm able to reproduce this problem, but not sure what the best fix is: odds are that, since this DOM ordering is part of the templates we've given to other agencies, there are now tons of sites that use this DOM ordering. If we change the DOM ordering, we'd likely have to change the CSS to ensure that the visual appearance stays the same--but then when other sites upgrade their version of USWDS, it might break their sites, unless they manually update their DOM ordering too, which could be a big hassle for them.

Arg.

**Comment by toolness** [comment] 2017-07-17 15:35
Actually, this might be easier than I thought, because our CSS appears to be a lot more flexible than I thought (see e.g. #2037).  But, that said, this still won't fix the websites that use the incorrect DOM ordering, since they've copypasta'd our incorrect templates.

**Comment by thisisdano** [comment] 2018-07-19 21:20
Thanks for contributing to USWDS. Unfortunately, this issue is not on our current [product roadmap](https://designsystem.digital.gov/whats-new/product-roadmap/).

**Closed by thisisdano** 2018-07-19 21:20 UTC
Labels: Under consideration, [Skill] Accessibility, [Skill] Front end, [Skill] UX, [Source] USA.gov
