### ISSUE TITLE
USWDS - Bug: Cancel File Input Browsing 

### ISSUE THREAD

**Issue by danbrady** [uswds/uswds#5781] opened 2024-02-21 14:42 UTC
### Describe the bug

After successfully attaching a file, if a user attempts to add a new/different file but cancels out from the file browse window, the original file disappears, essentially reinitializing the component.

(Not sure if this is intended or a bug?) 

### Steps to reproduce the bug

1. Go to File Input component
2. Add a file to component, see successful upload
3. Click to add a new/different file
4. Hit "Cancel" in file browser instead
5. Notice original file is removed

### Expected Behavior

I would expect cancelling the second file browse would retain the original selected file. 

### System setup

USWDS 3.5.0
Browser: Chrome v121
OS: Mac Sonoma

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by brunerae** [comment] 2024-02-23 17:56
Potentially relates to #4848 / #5212

**Comment by mahoneycm** [comment] 2024-02-26 18:05
Closing in favor of #5212 because this is a duplicate of the behaviors reported.

For reference, #4848 is a separate feature request to reset the file input via JavaScript.

**Closed by mahoneycm** 2024-02-26 18:05 UTC
Labels: Type: Bug, Needs: Confirmation
