### ISSUE TITLE
Supporting a fixed sidenav

### ISSUE THREAD

**Issue by konklone** [uswds/uswds#1952] opened 2017-05-29 16:01 UTC
It'd be nice if the USWDS' excellent sidenav functionality could easily support a "fixed" sidenav that travels down the page as the user scrolls.

For some hand-spun examples of this approach:

* https://theunitedstates.io/licensing/
* https://konklone.com/post/switch-to-https-now-for-free

I know one could use the framed approach, such as https://standards.usa.gov/components/, but this isn't the same effect (and doesn't have the same usability properties, as the framed approach means two independent scroll bars).

**Comment by maya** [comment] 2017-10-11 21:40
Hi, thanks for opening this issue. We'll review this with our team and see how it fits on our roadmap. Stay tuned!

Also, it's some pretty simple CSS to do this. `position: sticky` and `top: 0`.

**Comment by maya** [comment] 2018-02-21 23:22
Duplicate of #1745, closing to move convo there.

**Closed by maya** 2018-02-21 23:22 UTC
Labels: [Priority] Minor, [Skill] UX, [Status] Idea
