### ISSUE TITLE
Combo box search results do not match user expectations

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds#5647] opened 2023-11-29 17:55 UTC
# Summary
Users expect first letter navigation when they type into a combo box for selecting states or countries. In other words, if they type "T," they expect to see results of states starting with the letter T, like Tennessee, Texas, etc. The current way the combo box functions is to show all results _containing_ the letter "t", so for example Connecticut may show up in results, confusing users.

# Observations
4 out of 5 participants in usability testing were confused by the search results. They were tasked with selecting "Texas" from U.S. states combo box in a form prototype. Those 4 users typed "T" and were confused that they did not get results for only states starting with "T," and often would just scroll down the whole list to get to Texas. One users commented that that would be especially annoying if you were navigating a long list of 200+ countries.

[Video clips](https://drive.google.com/file/d/1h7TnVkejKvQGhPamrcZ5Z6rZxRrNl5A7/view?usp=sharing) :lock:

# Affected user groups

- All users
- Screen reader users
- Screen magnification users

# Research method
Usability testing with 5 visually impaired participants. See [findings report ](https://github.com/uswds/uswds/wiki/Usability-research-findings-for-Q3-2023)for details.

# Recommendations for next steps

Currently there are no clear solution recommendations. The team discussed whether the unexpected behaviors could be avoided by updating the combo box results to be sorted by relevance rather than alphabetically. Another possibility is adding screen reader instructions to enter a search term. Is it possible or recommended to implement first-letter navigation?

# Next steps

Decide on a solution to mitigate the friction users experience with unexpected search results and test it again in a new round of usability testing.

**Comment by mejiaj** [comment] 2024-02-23 17:40
Assigning to @mahoneycm to add additional information.

**Comment by jaclinec** [comment] 2024-02-23 22:52
Adding the light [landscape analysis](https://docs.google.com/document/d/1JfsnjWjIfbrKVB7JN9OsRcJXg306b7JX8xTTHf_MD_I/edit?usp=sharing) ([#338](https://github.com/uswds/uswds-team/issues/338)) for combo box to provide additional helpful info when thinking through a solution. Hoping to talk through some of this at a dev sync.

**Comment by mahoneycm** [comment] 2024-03-06 19:54
# W3C ARIA Keyboard Behaviors

## Combobox with editable input

Our current combo box most closely matches the [Editable Combobox With List Autocomplete Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/) found on the W3C patterns website.

### Keyboard behaviors

> This example illustrates the autocomplete behavior known as list autocomplete with manual selection. If the user types one or more characters in the edit box and the typed characters match the beginning of the name of one or more states or territories, a listbox popup appears containing the matching names. When the listbox appears, a suggested name is not automatically selected. Thus, after typing, if the user tabs or clicks out of the combobox without choosing a value from the listbox, the typed string becomes the value of the combobox. Note that this implementation enables users to input the name of a state or territory, but it does not prevent input of any other arbitrary value.

### Notable differences

- Dropdown list only displays items _starting_ with input.
  - When typing T, results are limited to Tennessee and Texas. Connecticut is excluded.
- Typing while dropdown list is focused
  - Recommendation from ARIA Authoring Group:
    - Moves visual focus to the textbox.
    - Types the character in the textbox.
    - Options in the listbox are filtered based on characters in the textbox.
  - Our behaviors
    - Currently, typing with the dropdown focused does not do anything
    - Dropdown selection and input are both unaffected 
    - Further, hitting shift + tab to return to the input causes the input test to be selected. Typing will then replace any previously typed query.

## Select-only combobox

I wanted to include the [Select-Only Combobox Example](https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-select-only/) because these behaviors are closer to the behaviors mentioned in this issue.

### Keyboard interaction

>- First opens the listbox if it is not already displayed and then moves visual focus to the first option that matches the typed character.
>- If multiple keys are typed in quick succession, visual focus moves to the first option that matches the full string.
>- If the same character is typed in succession, visual focus cycles among the options starting with that character.

These patterns match much closer to what the testers were expecting. The primary difference is without the editable input, we can focus on keyboard controls to iterate and search through the dropdown options.

**Comment by jaclinec** [comment] 2024-04-04 19:48
After discussing at a CS/UX sync, we decided we'd like to move forward with implementing a solution similar to Elastic UI's combobox where first letter navigation is prioritized, but that it also returns results with characters contained in the search terms. See [meeting notes](https://docs.google.com/document/d/1IAs5HfPXmD3zWRVB5H_ia2HHXMb5yt-gUqJiUectGWQ/edit?usp=sharing) and [Mural board](https://app.mural.co/t/gsa6/m/gsa6/1712087227154/247458a5071f39b8b46f5e059647b867330f5ae8?sender=u83d0e400125d69b595f75755).

We're aiming to get this solution in a testable condition in time for Buffalo batch re-testing at the end of May.

**Comment by mejiaj** [comment] 2024-05-21 14:21
Removing the discussion label because the April 4 comment shows that this was already discussed.

> After discussing at a CS/UX sync, we decided we'd like to move forward with implementing a solution similar to Elastic UI's combobox where first letter navigation is prioritized, but that it also returns results with characters contained in the search terms. See [meeting notes](https://docs.google.com/document/d/1IAs5HfPXmD3zWRVB5H_ia2HHXMb5yt-gUqJiUectGWQ/edit?usp=sharing) and [Mural board](https://app.mural.co/t/gsa6/m/gsa6/1712087227154/247458a5071f39b8b46f5e059647b867330f5ae8?sender=u83d0e400125d69b595f75755).
> 
> We're aiming to get this solution in a testable condition in time for Buffalo batch re-testing at the end of May.

**Comment by jaclinec** [comment] 2024-05-21 15:54
@mejiaj yes, I think we should still prioritize this work so we have a solution ready to test hopefully within the next few sprints.

**Comment by jaclinec** [comment] 2024-10-18 14:18
Considering findings and recommendations from the [combo box landscape analysis](https://docs.google.com/document/d/1JfsnjWjIfbrKVB7JN9OsRcJXg306b7JX8xTTHf_MD_I/edit?usp=sharing) :lock: done earlier this year and conversations in CS UX sync from last April, it looks like we decided to try implementing a combo box solution similar to[ Elastic UI's](https://eui.elastic.co/#/forms/combo-box#sorting-matches) where first letter navigation is prioritized, but that it also returns results with characters contained in the search terms. Kind of a "best of both worlds." 

Elastic UI example:
![Image](https://github.com/user-attachments/assets/99fe729f-07aa-4d96-b877-c2d4b93ee05a)

**Closed** 2024-11-12 16:09 UTC
Labels: Type: Bug, Affects: Accessibility 🟡, Package: Combo Box, Affects: Usability, Usability Testing, A11y Audit

**Comment by mejiaj** [comment] 2024-12-23 17:33
This is a duplicate of #5522.
