### ISSUE TITLE
striped tables

### ISSUE THREAD

**Issue by bruffridge** [uswds/uswds#2366] opened 2018-02-22 20:27 UTC
One of our developers requested the ability to add striped table rows. They said it aids readability on large data tables.

Something like this:
https://getbootstrap.com/docs/4.0/content/tables/#striped-rows

**Comment by maya** [comment] 2018-02-22 20:32
Hi @bruffridge, thanks for the issue. Seems like a duplicate of #1636. Would you mind re-posting it there to keep the conversation in one place? Thanks!

**Closed by maya** 2018-02-22 20:32 UTC
