### ISSUE TITLE
[Govt banner]: Display broken in IE 9-11

### ISSUE THREAD

**Issue by maya** [uswds/uswds#1984] opened 2017-06-19 20:40 UTC
The "This is how you know" button drops to the next line below the text, rather than appearing inline with the text. In IE 11, the end of the text "government" gets cut off to "governme", but not in IE 9.

FYI IE Edge seems to work fine.

## This is what I see (IE 11):
<img width="1212" alt="screen shot 2017-06-19 at 1 35 15 pm" src="https://user-images.githubusercontent.com/5249443/27304921-9317ceae-54f4-11e7-8033-6d95e482e77e.png">

## This is what I expect to see: 
<img width="1104" alt="screen shot 2017-06-19 at 1 37 22 pm" src="https://user-images.githubusercontent.com/5249443/27304916-903c363e-54f4-11e7-9ba6-a8af79c89d1d.png">

**Comment by bruffridge** [comment] 2017-06-27 23:20
Duplicate of: https://github.com/18F/web-design-standards/issues/1922

**Comment by maya** [comment] 2017-06-27 23:33
Oof that's a bummer that expandable content isn't working bc this could be used for a lot of other banner-like content. Thanks for catching that @bruffridge!

**Comment by toolness** [comment] 2017-06-30 14:11
A really weird thing about IE11, at least on Windows 10, is that the "governme" cut-off is not reliably reproducible.  It *might* only show up on a cold cache, as I've had trouble reproducing it even after the first load.

However, as @bruffridge mentioned, this is a duplicate of #1922, and shawn closed that because he said "as of 1.1, the banner no longer has any collapsible content".  Yet the [landing page template](https://standards.usa.gov/page-templates/landing/) on the `develop` branch of the docs, and the current live site, *does* have collapsible content--does that mean we should remove the collapsible content on the docs templates?

**Comment by toolness** [comment] 2017-06-30 15:50
Oh, I guess https://github.com/18F/web-design-standards-docs/issues/315 might have something to do with this.

I am still confused though.

**Comment by aileendds** [comment] 2017-11-27 22:23
We're running into this issue too. I see this block of CSS in IE10's developer tools style window but none of the rules are being applied: https://github.com/18F/web-design-standards/blob/9ff31e9e2c8906246b79d233116ef842cbc5a52c/src/stylesheets/components/_banner.scss#L140

**Comment by bonez0607** [comment] 2018-01-30 01:46
From what I could see when inspecting it appears that the class `.usa-banner-button` has `width: 100%` that overrides `width: initial` in IE11, that doesn't happen in Chrome. It appears changing it to `width: auto` (at least within developer tools) resolves the issue in IE11 keeps everything on one line.

**Closed** 2018-01-30 17:33 UTC
Labels: [Priority] Major, [Skill] Front end, [Type] Bug

**Comment by maya** [comment] 2018-01-30 17:43
Fixed in #2329, thanks for the help @bonez0607!
