### ISSUE TITLE
USWDS - Bug: Bad inits and teardowns on Uswds components when multiple instances in template in modern JS frameworks

### ISSUE THREAD

**Issue by rachidatecs** [uswds/uswds#5062] opened 2022-12-05 14:59 UTC
### Describe the bug

In JS frameworks (React, Vue, Angular) when multiple instances of a dynamic uswds components are dynamically created (modals, datepickers...), calling init/on in the create lifecycle and off in the destroy lifecycle is often buggy and results in multiple inits or off() on components that are already torn down. A fix that works for the modals in Nuxt builds is presented in PR #5031, not tested in Angular or React builds.

### Steps to reproduce the bug

1. Require a dynamic JS component (example: modal) in a modern JS framework implementation (eg Nuxt)
2. init in the created lifecycle hook
3. Tear down in the destroy lifecycle hook
4. have multiple instances on that component (example: 2 modals) in the template
5. Note that the first modal will get init once as expected, the second modal will get init twice

### Expected Behavior

To use the modal example from the scenario described above, I expect each instance of modal in the template to get initiated once.

### Related code

created() {
    // initialize
    modal.on();
  }

  // remove event listeners when the component un-mounts.
  beforeDestroy() {
    modal.off();
  }

### System setup

- USWDS 3.1.0
- Windows 10
- All modern browsers (FF, Chrome, Edge)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://designsystem.digital.gov/about/community/#community-conduct).
- [X] I checked the [current issues](https://github.com/uswds/uswds/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22) for duplicate bug reports.

**Comment by devkinetic** [comment] 2023-01-04 18:05
I'm running into this with modals and accordions. The PR in 5031 is working for the modals, but for accordions, the init is fired twice and clicking a heading toggle it open then closed.

**Comment by rachidatecs** [comment] 2023-01-04 21:47
@devkinetic, try doing the same thing for accordion inits and destroys: https://github.com/uswds/uswds/pull/5031/commits/5d385211214154c47af7d37c8c10a0091d5711f2

You can test for existing instances in your own app before taking the edit to the uswds package. Which js framework are you using?

**Comment by devkinetic** [comment] 2023-01-05 14:15
I'm using a Drupal block to render a modal with an accordion inside. Drupal implements BigPipe, So on domready when uswds.js starts, I have only a placeholder div. Once the html is loaded, I have an ajax callback to init my modal and accordions, so pretty benign.

```js
import modal from "uswds/src/js/components/modal";
import accordion from "uswds/src/js/components/accordion";

(function (once, modal, accordion) {
  'use strict';
  Drupal.behaviors.mobileSearchModal = {
    attach: function (context) {
      once('testing', '#testing').forEach(function (element, index) {
        // accordions still do not work due to a double event
        accordion.on();
        // modals will work only after patching for https://github.com/uswds/uswds/pull/5031
        modal.on();
      });
    }
  }
})(once, modal, accordion);
```

**Comment by rachidatecs** [comment] 2023-01-05 15:22
Could it be that your main load of uswds.js or navigation component (which requires accordions) is successfully calling accordion init? Did you try removing accordion.on() from that block of code above?

**Comment by devkinetic** [comment] 2023-01-05 16:41
If I remove `accordion.on()` the accordion does not init. The reason being that when the main load of uswds.js fires, that html is not in the dom. The accordion HTML only exists after the ajax completes, at which point I respond to it with my code sample. 

After accordion.on() is called, it does get the default functionality (first item open, others closed) but clicking on a heading will actually click twice, opening and closing the accordion content.

**Comment by rachidatecs** [comment] 2023-01-06 14:46
Maybe try approaching this from the other side; comment out the accordion module in uswds.js and see if things work as expected for you. You could also add some console logs to the unit methods in uswds.js and the uswds/src/js/components/accordion package to confirm that the issue is indeed accordion method firing twice.

**Comment by mahoneycm** [comment] 2023-01-24 17:49
Hey there @rachidatecs! Thank you for bringing this to our attention. 

I was unable to reproduce the bug while testing with Angular and React. Would you be able to create a test repo with your current setup so we can take a closer look? 

Thanks!

**Comment by rachidatecs** [comment] 2023-02-03 20:49
Hi @mahoneycm, I'll create a test repo whenever I get a chance and will follow up here.

**Comment by mahoneycm** [comment] 2023-02-03 22:56
@mahoneycm thank you! 👍

**Comment by rachidatecs** [comment] 2023-03-10 17:24
I don't believe so. Looks like 5049 fixes a propagation issue with some elements nested in modals. This (5062) is related to a an issue we see when a page contains multiple modal components causes the init() that's called from said components to create additional instances of the dynamically generated modal markup. Thanks for the prod Dave, I'll create a repo that reproduces this issue this evening.

**Comment by rachidatecs** [comment] 2023-03-10 23:06
@mahoneycm, thank you for your patience, it took me a while to get that repo up... Here it is: https://github.com/rachidatecs/uswds-modals

It's straightforward Angular and Uswds, with a modal component that requires the modal package and calls on/off on component init and destroy. Note that on the page with a single instance of the modal component, all works as expected. On the page with 2 instances of the modal component, the markup _for each of the modals_ gets created twice.

![Screen-Shot-2023-03-10-at-6 03 45-PM](https://user-images.githubusercontent.com/107004823/224444499-7a1d6282-2f1e-465a-9ff1-145b83f9e991.jpg)

**Comment by mahoneycm** [comment] 2023-03-21 15:06
Hey there @rachidatecs,

Thank you so much for creating this test repo! I see why I was unable to reproduce the error now.

The error appears to happen due to the modal's initialization being called more than once on the same page. During my testing, I found you can avoid this by only initializing the component one time. I did this by calling the initialization within the root `AppComponent` in both Angular and React. I was able to do this in your test repo by removing `modal.on/off` logic from the modal component and implementing it in `app.component.ts`

Angular Example:
``` ts
//@ts-ignore
import modal from "@uswds/uswds/js/usa-modal";

...

export class AppComponent implements OnInit {
  ngOnInit() {
    throw new Error('Method not implemented.');
  }
  title = '5062-modal-inits';

  // Initializing modal on app start

  ngAfterViewInit() {
    modal.on();
  }

  ngOnDestroy() {
    modal.off();
  }
}
```

This could have also been done in the `one-modal` or `multiple-modals` components as long as each `modal.on/off()` function is only being called once per lifecycle hook.

Since this replicates standard js initialization and falls in line with our [JS framework documentation](https://designsystem.digital.gov/documentation/developers/#js-customization-2), we aren't going to consider this a breaking bug, but we understand the need to improve component initialization. I'm hoping to dig deeper into the component logic and see if we can modify it to allow for initialization at the component level as you're suggesting! I'll take another look at your recommendation in #5031 and see what performing this check within our initialization would look like.

**Comment by rachidatecs** [comment] 2023-03-21 22:12
@mahoneycm thanks so much for taking a look at this.

My turn to maybe missing something, but implementing on()/off() at the root level will cause the initially unmounted instances to not initialize. In other words, whatever page/component is visible when you load the app will work fine, whatever page/component gets mounted after app load will not work.

To illustrate, I just created branch init-in-root. Just navigate between the pages.

**Comment by rachidatecs** [comment] 2023-03-22 16:30
@mahoneycm yes! Page level inits is a beautiful workaround. There's something to be said about keeping components self-contained though, so a component level check to make sure inits and destroys are handles correctly when multiple instances exist would be nice. And more resilient.

**Comment by rachidatecs** [comment] 2023-03-22 17:33
Note that this issue might exist on other components that similarly inject and destroy DOM elements, such as file input and date picker.

**Comment by mejiaj** [comment] 2023-07-27 20:36
Adding this discussion comment as further evidence. 

[Trying to use USWDS modal. Works if I don't pass argument to on method, doesn't work if I do #5390](https://github.com/uswds/uswds/discussions/5390)

**Closed** 2023-10-30 23:16 UTC
Labels: Type: Bug
