### ISSUE TITLE
Publish draft component principles and guidance to website

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds#3168] opened 2019-11-06 20:19 UTC
- Draft the principles and preliminary guidance   
- -	Publish draft component principles and guidance to website

**Comment by pglevy** [comment] 2019-11-07 22:16
Acceptance Criteria:
Assure alignment with USWDS service and product principles (Answers to questions of Service and USWDS Product principles describing how the component is adhering to them.)

**Comment by pglevy** [comment] 2019-11-07 22:26
Duplicate of #3166

**Closed by pglevy** 2019-11-07 22:26 UTC
Labels: [Component] Card
