### ISSUE TITLE
External icon link display issue in Safari

### ISSUE THREAD

**Issue by amyleadem** [uswds/uswds#4413] opened 2021-11-30 16:22 UTC
Description:
In Safari, the external link icon has a display bug where the icon mask does not fully cover the background color. This results in the background color showing through and displaying colored lines that surround the icon. 
This issue might affect other masked icons in the system as well.

Steps to reproduce:
1. Open any page on https://designsystem.digital.gov/
2. Observe all external links to see the background color show through

Expected behavior:
Icons should not allow any background color to display around the svg

Screenshots:
![image](https://user-images.githubusercontent.com/93996430/144086126-06c2d580-2271-4272-99b3-8402b1560fac.png)

![image](https://user-images.githubusercontent.com/93996430/144085167-34e704fa-c97f-4ed5-be07-48aaf8045c7d.png)

System setup
- USWDS version: 2.12.2
- Device: MacBook Pro
- Operating system: MacOS 12.0.1
- Browser and version: Safari 15.1

Possible solution:
1. Set the mask-size to “cover”
	-Please note: This approach will make the icon size larger. Consider adjusting the icon svg to include more padding inside the graphic itself

**Comment by aduth** [comment] 2022-01-30 16:37
I believe this is a duplicate of #4434, fixed now as of v2.13.1?

>**Fix external link icon display bug in Safari.** We fixed a bug that resulted in colored bars on the top and bottom of external link icons in Safari. (#4439)

https://github.com/uswds/uswds/releases/tag/v2.13.1

**Comment by mejiaj** [comment] 2022-02-23 20:35
Yes, thank you @aduth. This is a duplicate and I'll close since the PR got merged.

**Closed by mejiaj** 2022-02-23 20:35 UTC
