### ISSUE TITLE
Sub-links in header menu have too small a target

### ISSUE THREAD

**Issue by swirtSJW** [uswds/uswds#3033] opened 2019-04-12 18:16 UTC
## When I expand the dropdown in a menu, the submenu items target is only the link text rather than the full width and height of the menu element.   This has some accessibility issues.

I expect that when my mouse is over a menu item in the expanded state (on desktop) I can click and go to the page without having to be certain to click only on the text in the menu item.

## Steps to reproduce the issue

1. Click on a level one menu item to expand it.
2. Try to activate a sub-menu element item by clicking near the text but not on the text.

## Additional information [optional]

* Screen shot images
![image](https://user-images.githubusercontent.com/5752113/56057717-87840b00-5d2d-11e9-8354-5c9bd162c7b7.png)

**Comment by maya** [comment] 2019-04-12 18:23
Hi @swirtSJW, thank for opening this issue. This looks like a duplicate of #2836. Could you add your comments to that issue so we can keep the conversation in one place?

**Comment by maya** [comment] 2019-04-12 19:37
Moved content to #2836, closing duplicate issue.

**Closed by maya** 2019-04-12 19:37 UTC
