### ISSUE TITLE
Rename footer section classes

### ISSUE THREAD

**Issue by donjo** [uswds/uswds#2332] opened 2018-02-05 18:55 UTC
The footer has a few classes that are incorrectly named given our naming pattern. More information can be found in PR #2330 

Because renaming these without doubling up on the classes and leaving some deprecated ones behind would be a breaking change, we'll take care of this in 2.0

**Comment by maya** [comment] 2018-02-21 23:41
Just realized this is a duplicate of #1505.

**Closed by maya** 2018-02-21 23:41 UTC
Labels: 2.0, [Skill] Front end, [Type] Bug, [Type] Enhancement
