### ISSUE TITLE
Cards inside grid-row and grid-col cause issues in IE11

### ISSUE THREAD

**Issue by stphnwlkr** [uswds/uswds#3471] opened 2020-05-14 12:54 UTC
When I placed a simple three card layout inside a grid-row+grid-col-12, the layout in IE11 was broken. It appars that this combination overrides the card settings. Attached are images comparing Edge Chromium and IE11.

**Inside grid-row grid-col-12**

![inside-grid-row](https://user-images.githubusercontent.com/1405187/81936532-75c00780-95c0-11ea-8523-2d858e8d822c.jpg)

**Removing the cards from the grid-row gid-col combinationation resolved the problem**

![grid-row and grid-col removed](https://user-images.githubusercontent.com/1405187/81936517-7062bd00-95c0-11ea-8b6e-c998aa7684c0.jpg)

**Comment by mejiaj** [comment] 2020-05-14 13:38
@stphnwlkr could you provide some of the markup you used so I can reproduce this issue and debug?

The cards come with their own grid setup via a parent `usa-card-group` wrapper.

**Comment by stphnwlkr** [comment] 2020-05-14 13:47
@mejiaj It was actually an accident that it was left within a grid-row grid-col combination, but it worked fine in all browsers except IE. It literally was just the base card setup inside grid-row and grid-col-12

`<div class="grid-row">
        <div class="gid-col-12">
          <ul class="usa-card-group">
            <li class="tablet:grid-col-4 usa-card">
              <div class="usa-card__container">
                <header class="usa-card__header">
                  <h2 class="usa-card__heading">Title</h2>
                </header>
                <div class="usa-card__media">
                  <div class="usa-card__img"> <img src="" alt=""> </div>
                </div>
                <div class="usa-card__body"> </div>
                <div class="usa-card__footer"> </div>
              </div>
            </li>
            <li class="tablet:grid-col-4 usa-card">
              <div class="usa-card__container">
                <header class="usa-card__header">
                  <h2 class="usa-card__heading">Title</h2>
                </header>
                <div class="usa-card__media">
                  <div class="usa-card__img"> <img src="" alt=""> </div>
                </div>
                <div class="usa-card__body"> </div>
                <div class="usa-card__footer"> </div>
              </div>
            </li>
            <li class="tablet:grid-col-4 usa-card">
              <div class="usa-card__container">
                <header class="usa-card__header">
                  <h2 class="usa-card__heading">Title</h2>
                </header>
                <div class="usa-card__media">
                  <div class="usa-card__img"> <img src="" alt=""> </div>
                </div>
                <div class="usa-card__body"> </div>
                <div class="usa-card__footer"> </div>
              </div>
            </li>
          </ul>
        </div>
      </div>`

**Comment by mejiaj** [comment] 2020-05-14 14:00
Thanks, I just wanted to make sure. Looking into it now.

**Comment by mejiaj** [comment] 2020-05-14 14:50
@stphnwlkr, this seems to be working as intended.

The image dimensions might be the cause of the issue. I was able to reproduce with an 800x600 image and I was able to fix it with the `add-aspect-1x1` and `pin-all` classes.

Attached is the markup for the image:
```html
<div class="usa-card__img add-aspect-1x1"> 
  <img class="pin-all" src="https://images.unsplash.com/photo-1579800070193-abe62433f737?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=610&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ" alt="">
</div>
```

You can read more about it on the Card page under `Implementation`

https://designsystem.digital.gov/components/card/

![image](https://user-images.githubusercontent.com/3385219/81949238-3b5a6880-95c8-11ea-984c-e56b240abe8e.png)

**Comment by stphnwlkr** [comment] 2020-05-15 12:49
I am taking a look at this. All the images are 16:9 so this should not be an issue It is possible the pin-all (undocumented?) class may fix it. I honestly would not spend a lot of time on this, but for the near future the default browser at VA is IE11 (changing soon supposedly, but not holding my breath).

**Comment by mejiaj** [comment] 2020-06-03 14:36
I was looking at this suspecting it would be related to issue #3386; which involves flex shorthands not displaying properly in IE11.

You can view the preview [here](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-test-flex/components/preview/flex.html) at the bottom of the page.

There are 2 examples:

![image](https://user-images.githubusercontent.com/3385219/83649558-f4cfac80-a57c-11ea-8e2b-7266b4fc4bb8.png)

The first one is based on the example posted [above](https://github.com/uswds/uswds/issues/3471#issuecomment-628647696). 

```html
 <div class="gid-col-12">
```

If you fix the typo above everything displays as expected in all browsers.

### IE11
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/3385219/83650148-a242c000-a57d-11ea-9fcb-8f50459c2fac.png">

**Comment by thisisdano** [comment] 2020-06-16 16:22
Fixed in https://github.com/uswds/uswds/pull/3480

**Closed by thisisdano** 2020-06-16 16:22 UTC
Labels: topic: IE11, type: bug
