### ISSUE TITLE
Selected radio buttons and checkboxes do not print consistently

### ISSUE THREAD

**Issue by stevenbuccini** [uswds/uswds#3137] opened 2019-10-23 16:23 UTC
## Description
We want users to be able to print a copy of a completed form. Rather than generate a new page with the given information, we simply use a custom stylesheet specifically for printing. 

Here is how a radio/check input types render on the page: 
![image](https://user-images.githubusercontent.com/2475615/67413718-fa661c80-f5c1-11e9-9bbb-54459e995031.png)

And here's how they look when printing:
![image](https://user-images.githubusercontent.com/2475615/67413830-339e8c80-f5c2-11e9-8844-fe4331e97200.png)

As you can see, the outlines of the checkbox/radio button are highlighted in blue but it is very, very hard to see. Ideally, they would match how they look on the page.

## Steps to reproduce the issue

1. Throw some inputs into the DOM, toggle them on
2. Pull up the print dialog.

**Comment by thisisdano** [comment] 2019-12-03 05:58
I'm having trouble confirming this. What browser, operating system, and USWDS version are you using?

**Comment by stevenbuccini** [comment] 2019-12-04 18:30
Browser: Firefox/Chrome (latest)
OS: MacOS Mojave

We uncovered this bug while using the Benjamin Wordpress theme. That developer recommended filing the ticket here. [Looking in the source](https://github.com/kyle-jennings/benjamin/blob/dev/assets/frontend/css/benjamin.css), I don't see a direct mapping to the USWDS code or a particular version number.

**Comment by mejiaj** [comment] 2019-12-06 20:59
I'm not able to reproduce consistently.

Browser: Firefox & Chrome
OS: OSX Mojave

I've only noticed the `checked` checkbox sometimes doesn't show the icon, but when you close and try again it does.

**Comment by thisisdano** [comment] 2021-02-23 23:44
I'm still seeing this issue even though I though we'd addressed long ago. Let's revisit it as part of the followup on Accelerator's print stylesheets work

**Comment by thisisdano** [comment] 2021-02-24 21:40
Issue #3312 indicates that sometimes they only print on multiple attempts. I'm closing that issue so we can use this one for addressing radio and checkbox print issues.

**Comment by mejiaj** [comment] 2021-06-15 14:57
I see this in Chromium browsers on first page load with checkbox. 

I've tried setting the print styles with `!important` and using `color-adjust: exact !important` to try to have the checkbox show up on print. Neither works reliably.

There are additional settings in print options that will allow you to display the icon:


https://user-images.githubusercontent.com/3385219/122075822-f81c8b80-cdbf-11eb-9e11-f9d28f305b93.mp4

**Closed** 2021-12-09 18:48 UTC
Labels: bug, skill: front end, affects: checklist, affects: radio button
