### ISSUE TITLE
Mega menu javascript bug with Firefox: Uncaught TypeError: t.target.closest is not a function

### ISSUE THREAD

**Issue by pgoddardmobomo** [uswds/uswds#3594] opened 2020-08-22 19:58 UTC
## Description

In Firefox (v79 is what I'm using), when looking at dev console, and while hovering over non-active menu items, the following error appears:

`Uncaught TypeError: t.target.closest is not a function`

Error does not seem to break functionality, though.

## Steps to reproduce the issue

1. Visit https://components.designsystem.digital.gov/components/detail/header--basic-mega.html
2. Open Developer Tools and select Console tab.
3. While console is open, hover over non-active menu item.

![Screen Shot 2020-08-22 at 12 56 14 PM](https://user-images.githubusercontent.com/69162966/90964624-12732a80-e477-11ea-949c-ab731f8b200a.png)

**Comment by kkoskelin** [comment] 2020-09-21 21:31
It seems that `receptor/delegate`'s `index.js` attempts to call `event.target.closest` when the event.target is actually a text node.  This is producing an error since text nodes do not have `closest` functionality.  This may be a Firefox bug, or perhaps an implementation bug, unsure. A fix could be added to this dependency checking `if(event.target.nodeType === 3) { /* return*/ }`

**Comment by davemcorwin** [comment] 2021-01-26 20:16
I am seeing this as well

**Comment by duncan-truss** [comment] 2021-02-24 16:50
Can confirm this has been an issue for me for a while now.  I primarily use Firefox as well.

**Comment by mahoneycm** [comment] 2021-09-16 19:29
After some testing, I can confirm this error has been corrected in the latest instance of USWDS! I am able to reproduce the error in 2.11.0 but not 2.12.1.

**Comment by mejiaj** [comment] 2021-09-16 19:34
Not seeing it on 2.12.1.

@thisisdano this is safe to close.

**Comment by aduth** [comment] 2022-01-30 17:44
Likely a duplicate of #4184, fixed by #4256.

**Closed** 2022-05-07 05:39 UTC
Labels: Bug, Javascript, Affects: Sidenav
