### ISSUE TITLE
[Dropdown]: Safari quadruple arrows

### ISSUE THREAD

**Issue by joshbruce** [uswds/uswds#2417] opened 2018-03-29 15:45 UTC
## Description

Safari displays four arrows.

## Steps to reproduce the issue

1. Safari 11.0.3
2. Navigate to https://designsystem.digital.gov/components/form-controls/#dropdown
3. See attached

<img width="484" alt="screen shot 2018-03-29 at 11 43 30 am" src="https://user-images.githubusercontent.com/15252830/38098653-a6ac4b30-3346-11e8-89bf-efde3ba63470.png">

**Comment by joshbruce** [comment] 2018-03-29 15:47
Same in Chrome

**Comment by joshbruce** [comment] 2018-03-29 15:47
Similar in FF

<img width="392" alt="screen shot 2018-03-29 at 11 47 40 am" src="https://user-images.githubusercontent.com/15252830/38098841-041a55e6-3347-11e8-9108-50b49f103d37.png">

**Comment by joshbruce** [comment] 2018-03-29 15:57
Ended up prefixing.

```css
	appearance: none;
	-webkit-appearance: none;
	-moz-appearance: none;
	background: #ffffff;
	background-image: url("../img/arrow-both.svg");
	background-position: right 1.3rem center;
	background-repeat: no-repeat;
	background-size: 1rem;	
```

**Comment by hursey013** [comment] 2018-03-29 16:00
@joshbruce are you using Sass to compile your stylesheets?

**Comment by maya** [comment] 2018-03-29 16:06
Duplicate of #523.

**Comment by hursey013** [comment] 2018-03-29 16:07
Nevermind... just actually read your issue and see that you are referencing https://designsystem.digital.gov

Looks like this is related to https://github.com/uswds/uswds-site/issues/523

**Closed** 2018-03-29 16:08 UTC

**Comment by joshbruce** [comment] 2018-03-29 16:19
@hursey013: Yes. It was happening on the 8fold site. Only referenced the DS site because it was there as well. What are you using to add the prefixes. Believer Bourbon is deprecating their implementations and asking folks to use packages specifically designed for that purpose.
