### ISSUE TITLE
[Form controls]: Date input + Safari helpers

### ISSUE THREAD

**Issue by joshbruce** [uswds/uswds#2339] opened 2018-02-12 15:31 UTC
## Description

For the `number` type on `text inputs` Safari will add the up and down UI helper.

## Steps to reproduce the issue

1. Open Safari in High Sierra
2. Go to date input: https://designsystem.digital.gov/components/form-controls/#date-input
3. Focus on the field
4. See what appears to be a quick fill option

## Additional information [optional]

<img width="236" alt="screen shot 2018-02-12 at 10 21 22 am" src="https://user-images.githubusercontent.com/15252830/36104371-d3db7b9c-0fdf-11e8-89b2-4bdef9fe3c2e.png">

**Comment by maya** [comment] 2018-02-12 19:43
Hi @joshbruce, thanks for pointing this out. Unfortunately, GSA IT has not given us approval to use High Sierra so we're unable to test this out just yet.

**Comment by donjo** [comment] 2018-02-12 19:58
I looked into this on my personal machine and it seems like that's just the styling Safari uses for autofill now (the dropdown is to pick which name/profile you want to fill).

Were you just curious where this is coming from, suggesting we disable it if possible, or wondering if the USWDS could profile style overrides for it? (or something else)

**Comment by joshbruce** [comment] 2018-02-12 20:06
Hey @donjo, fair questions.

Back in the day there was a decision made by the USWDS to remove the secondary UI components from the component (#1076). We decided to hide those using some `webkit-` styles, I think (??). Was just letting everyone know that it's back.

**Comment by maya** [comment] 2018-07-20 02:35
Duplicate of #1972.

**Closed by maya** 2018-07-20 02:35 UTC
Labels: [Priority] Minor, [Skill] Front end
