### ISSUE TITLE
Develop Design for Pager Elements

### ISSUE THREAD

**Issue by RonWilliams** [uswds/uswds#2436] opened 2018-04-17 17:32 UTC
## Description

The current design system supports buttons, labels, form elements etc, but it seems to be missing "pager" / "paging" elements. I think a common look and feel for those elements would help user experience and provide a consistent experience across the site.

**Comment by stphnwlkr** [comment] 2018-04-24 00:12
I believe he is referring to pagination for large data sets or even simple next and previous. Bootstrap example http://getbootstrap.com/docs/4.1/components/pagination/

**Comment by maya** [comment] 2018-04-24 00:26
Ah, if so, that's already opened here: #959. Let me know if that's what you're referring to @RonWilliams.

**Comment by maya** [comment] 2018-05-14 18:25
Closing as it's a duplicate of #959.

**Closed by maya** 2018-05-14 18:25 UTC

**Comment by RonWilliams** [comment] 2018-05-24 00:08
Hi @maya and @stphnwlkr --
This is correct, my request was related to pager/pagination in #959. Thank you for closing and cleaning up the issue queue. Sorry about the duplicate.
