### ISSUE TITLE
USWDS - a11y: Required fields paragraph being ignored in Voiceover Safari.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds#3947] opened 2021-01-15 19:52 UTC
### Describe the bug
Voiceover on Safari isn't reading the required form instructions at the top of forms with required field inputs.

Examples:
- [Address form](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-required-fields/components/preview/address-form.html)
- [Name form](https://federalist-3b6ba08e-0df4-44c9-ac73-6fc193b0e19c.app.cloud.gov/preview/uswds/uswds/jm-required-fields/components/preview/name-form.html)

> Required fields are marked with an asterisk (*). 

### Steps to reproduce the bug
1. Open preferences and ensure you have `Change the way Tab moves focus` enabled in `Preferences ▸ Keyboard ▸ Keyboard (left side nav)`.
2. Open links above in Safari
3. Enable voiceover
4. Start tabbing throughout form

### Expected behavior
Voiceover _should_ read instructions.

### Screenshots
Add screenshots to help provide context, if applicable.

### System setup
- **USWDS version:** 2.10.0
- **Device:** Macbook
- **Operating system:** OSX Big Sur
- **Browser and version:** Safari 14.0.2

### Additional context
This is **only** happening in Safari. Voiceover on Chrome works as expected.

**Comment by mejiaj** [comment] 2021-09-24 18:30
On Safari 14.1 OSX Big Sur, you can navigate to the paragraph using <kbd>ctrl + shift + option</kbd> and the up and down arrows.

I would say this is safe to close.

**Comment by amyleadem** [comment] 2021-11-30 19:11
@mejiaj  Confirming that the required text content is accessible via VoiceOver keyboard navigation in Safari 15.1.
To access this content, user should press _VO_ + right- or left-arrow to navigate. This is expected behavior in Voiceover for non-focusable content.

**Comment by brunerae** [comment] 2021-12-22 15:51
Confirmed that this is not a bug. Moving to FFR.

**Closed** 2022-05-06 23:13 UTC
Labels: Accessibility
